name: Unit + UI Testing test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  unit-ui-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstraping packages
        run: yarn install
      - name: Testing Shared Utils
        if: always()
        run: yarn jest ./shared
      - name: Testing Storybook UI
        if: always()
        run: yarn storybook:build
